dynamic: install
install:
	cp -f libwlbcmcrypto.so_TELE2_save $(INSTALL_DIR)/lib/libwlbcmcrypto.so
	cp -f libwlbcmshared.so_TELE2_save $(INSTALL_DIR)/lib/libwlbcmshared.so
	cp -f bcmupnp_TELE2_save bcmupnp
	cp -f eapd_TELE2_save eapd
	cp -f lld2d_TELE2_save lld2d
	cp -f wrt54g.large.ico_TELE2_save wrt54g.large.ico
	cp -f wrt54g.small.ico_TELE2_save wrt54g.small.ico
	cp -f nas_TELE2_save nas
	cp -f nvram_params_TELE2_save nvram_params
	cp -f nvramUpdate_TELE2_save nvramUpdate
	cp -f wlctl_TELE2_save wlctl
	cp -f libwlctl.so_TELE2_save $(INSTALL_DIR)/lib/libwlctl.so
	cp -f libwlmngr.so_TELE2_save $(INSTALL_DIR)/lib/libwlmngr.so
	cp -f wps_monitor_TELE2_save wps_monitor
	cp -f wps_ap_TELE2_save wps_ap
	cp -f wps_enr_TELE2_save wps_enr
	cp -f libwps.so_TELE2_save $(INSTALL_DIR)/lib/libwps.so
