#!/bin/bash

ROOTFS=$PROFILE/fs


# Create FIFO devices

mknod $ROOTFS/dev/initctl p


#Create character devices
mknod $ROOTFS/dev/mem c 1 1
mknod $ROOTFS/dev/kmem c 1 2
mknod $ROOTFS/dev/null c 1 3
mknod $ROOTFS/dev/port c 1 4
mknod $ROOTFS/dev/zero c 1 5
mknod $ROOTFS/dev/ptyp0 c 2 0
mknod $ROOTFS/dev/ptyp1 c 2 1
mknod $ROOTFS/dev/ttyp0 c 3 0
mknod $ROOTFS/dev/ttyp1 c 3 1
mknod $ROOTFS/dev/tty0 c 4 0
mknod $ROOTFS/dev/tty1 c 4 1
mknod $ROOTFS/dev/ttyS0 c 4 64
mknod $ROOTFS/dev/ttyS1 c 4 65
mknod $ROOTFS/dev/tty c 5 0
mknod $ROOTFS/dev/console c 5 1
mknod $ROOTFS/dev/ptmx c 5 2
mknod $ROOTFS/dev/ppp c 108 0
mknod $ROOTFS/dev/printer0 c 180 0
mknod $ROOTFS/dev/urandom c 1 9


# Create Broadcom specific devices

mknod $ROOTFS/dev/bcmatm0 c 205 0
mknod $ROOTFS/dev/brcmboard c 206 0
mknod $ROOTFS/dev/bcmvdsl0 c 207 0
mknod $ROOTFS/dev/bcmadsl0 c 208 0
mknod $ROOTFS/dev/bcmendpoint0 c 209 0
mknod $ROOTFS/dev/bcmaal20 c 210 0
mknod $ROOTFS/dev/bcmles0 c 211 0
mknod $ROOTFS/dev/bcm c 212 0
mknod $ROOTFS/dev/ac97 c 222 0
mknod $ROOTFS/dev/slac c 223 0
mknod $ROOTFS/dev/bcmprof c 224 0
mknod $ROOTFS/dev/si3215 c 225 0
mknod $ROOTFS/dev/bcmatmb0 c 226 0
mknod $ROOTFS/dev/p8021ag0 c 227 0
mknod $ROOTFS/dev/bcmxtmcfg0 c 228 0
mknod $ROOTFS/dev/bcmgpon_bar3 c  229 0
mknod $ROOTFS/dev/bcmgpon_ploam c 230 0
mknod $ROOTFS/dev/bcmgpon c 231 0
mknod $ROOTFS/dev/pktcmf c 232 0
mknod $ROOTFS/dev/spu c 233 0
mknod $ROOTFS/dev/pwrmngt c 240 0

mknod $ROOTFS/dev/capi20 c 68 0
mknod $ROOTFS/dev/isdninfo c 45 255
mknod $ROOTFS/dev/ippp0 c 45 128
mknod $ROOTFS/dev/ippp1 c 45 129
mknod $ROOTFS/dev/isdnctrl0 c 45 64
mknod $ROOTFS/dev/isdnctrl c 45 64
mknod $ROOTFS/dev/isdn c 45 0


# Create block devices

mknod $ROOTFS/dev/ram0 b 1 0
mknod $ROOTFS/dev/ram1 b 1 1
mknod $ROOTFS/dev/ram2 b 1 2
mknod $ROOTFS/dev/ram3 b 1 3
ln -s ram1 $ROOTFS/dev/ram

mknod $ROOTFS/dev/mtdblock0 b 31 0
mknod $ROOTFS/dev/mtdblock1 b 31 1
mknod $ROOTFS/dev/mtdblock2 b 31 2
mknod $ROOTFS/dev/mtdblock3 b 31 3
mknod $ROOTFS/dev/mtdblock4 b 31 4
mknod $ROOTFS/dev/mtdblock5 b 31 5
mknod $ROOTFS/dev/mtdblock6 b 31 6
mknod $ROOTFS/dev/mtdblock7 b 31 7


# Char access to flash

mknod $ROOTFS/dev/mtd0  c 90 0
#mknod $ROOTFS/dev/mtdr0 c 90 1
mknod $ROOTFS/dev/mtd1  c 90 2
#mknod $ROOTFS/dev/mtdr1 c 90 3
mknod $ROOTFS/dev/mtd2  c 90 4
#mknod $ROOTFS/dev/mtdr2 c 90 5
mknod $ROOTFS/dev/mtd3  c 90 6
#mknod $ROOTFS/dev/mtdr3 c 90 7
mknod $ROOTFS/dev/mtd4  c 90 8
#mknod $ROOTFS/dev/mtdr4 c 90 9
mknod $ROOTFS/dev/mtd5  c 90 10
#mknod $ROOTFS/dev/mtdr5 c 90 11
mknod $ROOTFS/dev/mtd6  c 90 12
#mknod $ROOTFS/dev/mtdr6 c 90 13



# USB Mass Storage Devices
mknod $ROOTFS/dev/sda b 8 0
mknod $ROOTFS/dev/sda1 b 8 1
mknod $ROOTFS/dev/sda2 b 8 2
mknod $ROOTFS/dev/sda3 b 8 3
mknod $ROOTFS/dev/sda4 b 8 4
mknod $ROOTFS/dev/sda5 b 8 5
mknod $ROOTFS/dev/sda6 b 8 6
mknod $ROOTFS/dev/sda7 b 8 7
mknod $ROOTFS/dev/sda8 b 8 8
mknod $ROOTFS/dev/sda9 b 8 9
mknod $ROOTFS/dev/sda10 b 8 10
mknod $ROOTFS/dev/sda11 b 8 11
mknod $ROOTFS/dev/sda12 b 8 12
mknod $ROOTFS/dev/sda13 b 8 13
mknod $ROOTFS/dev/sda14 b 8 14
mknod $ROOTFS/dev/sda15 b 8 15
mknod $ROOTFS/dev/sdb b 8 16
mknod $ROOTFS/dev/sdb1 b 8 17
mknod $ROOTFS/dev/sdb2 b 8 18
mknod $ROOTFS/dev/sdb3 b 8 19
mknod $ROOTFS/dev/sdb4 b 8 20
mknod $ROOTFS/dev/sdb5 b 8 21
mknod $ROOTFS/dev/sdb6 b 8 22
mknod $ROOTFS/dev/sdb7 b 8 23
mknod $ROOTFS/dev/sdb8 b 8 24
mknod $ROOTFS/dev/sdb9 b 8 25
mknod $ROOTFS/dev/sdb10 b 8 26
mknod $ROOTFS/dev/sdb11 b 8 27
mknod $ROOTFS/dev/sdb12 b 8 28
mknod $ROOTFS/dev/sdb13 b 8 29
mknod $ROOTFS/dev/sdb14 b 8 30
mknod $ROOTFS/dev/sdb15 b 8 31
mknod $ROOTFS/dev/sdc b 8 32
mknod $ROOTFS/dev/sdc1 b 8 33
mknod $ROOTFS/dev/sdc2 b 8 34
mknod $ROOTFS/dev/sdc3 b 8 35
mknod $ROOTFS/dev/sdc4 b 8 36
mknod $ROOTFS/dev/sdc5 b 8 37
mknod $ROOTFS/dev/sdc6 b 8 38
mknod $ROOTFS/dev/sdc7 b 8 39
mknod $ROOTFS/dev/sdc8 b 8 40
mknod $ROOTFS/dev/sdc9 b 8 41
mknod $ROOTFS/dev/sdc10 b 8 42
mknod $ROOTFS/dev/sdc11 b 8 43
mknod $ROOTFS/dev/sdc12 b 8 44
mknod $ROOTFS/dev/sdc13 b 8 45
mknod $ROOTFS/dev/sdc14 b 8 46
mknod $ROOTFS/dev/sdc15 b 8 47
mknod $ROOTFS/dev/sdd b 8 48
mknod $ROOTFS/dev/sdd1 b 8 49
mknod $ROOTFS/dev/sdd2 b 8 50
mknod $ROOTFS/dev/sdd3 b 8 51
mknod $ROOTFS/dev/sdd4 b 8 52
mknod $ROOTFS/dev/sdd5 b 8 53
mknod $ROOTFS/dev/sdd6 b 8 54
mknod $ROOTFS/dev/sdd7 b 8 55
mknod $ROOTFS/dev/sdd8 b 8 56
mknod $ROOTFS/dev/sdd9 b 8 57
mknod $ROOTFS/dev/sdd10 b 8 58
mknod $ROOTFS/dev/sdd11 b 8 59
mknod $ROOTFS/dev/sdd12 b 8 60
mknod $ROOTFS/dev/sdd13 b 8 61
mknod $ROOTFS/dev/sdd14 b 8 62
mknod $ROOTFS/dev/sdd15 b 8 63
mknod $ROOTFS/dev/sde b 8 64
mknod $ROOTFS/dev/sde1 b 8 65
mknod $ROOTFS/dev/sde2 b 8 66
mknod $ROOTFS/dev/sdf b 8 80
mknod $ROOTFS/dev/sdf1 b 8 81
mknod $ROOTFS/dev/sdf2 b 8 82
mknod $ROOTFS/dev/sdg b 8 96
mknod $ROOTFS/dev/sdg1 b 8 97
mknod $ROOTFS/dev/sdg2 b 8 98
mknod $ROOTFS/dev/sdh b 8 112
mknod $ROOTFS/dev/sdh1 b 8 113
mknod $ROOTFS/dev/sdh2 b 8 114

# @ntfs-3g
mknod $ROOTFS/dev/fuse c 10 229
mknod $ROOTFS/dev/misc/fuse c 10 229

# @acosInit
mknod $ROOTFS/dev/acos_nat_cli  c 100 0
mknod $ROOTFS/dev/aglog         c 123 0
mknod $ROOTFS/dev/gpio_drv      c 124 0
